---
wemove:
  bootstrap:
    data:
      enabled: true
      services:
        - serviceCode: "001"
          serviceName: Cans left out 24x7
          description: Garbage or recycling cans that have been left out for more than 24 hours after collection. Violators will be cited.
          metadata: true
          type: realtime
          keywords:
            - sanitation
            - nuisance
          group: sanitation
        - serviceCode: "002"
          serviceName: Construction plate shifted
          description: Metal construction plate covering the street or sidewalk has been moved.
          metadata: true
          type: realtime
          keywords:
            - hazard
          group: street
        - serviceCode: "003"
          serviceName: Curb or curb ramp defect
          description: Sidewalk curb or ramp has problems such as cracking, missing pieces, holes, and/or chipped curb.
          metadata: true
          type: realtime
          keywords:
            - hazard
          group: street
