micronaut:
  application:
    name: app
  data:
    pageable:
      size-parameter-name: page_size
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
jpa:
  default:
    entity-scan:
      packages: "app.model"
    properties:
      hibernate:
        hbm2ddl:
          auto: ${DPD_AUTO_SCHEMA_GEN:update}
netty:
  default:
    allocator:
      max-order: 3
