gcp:
  project-id: local-motion-we-move

micronaut:
  application:
    name: app
  object-storage:
    gcp:
      default:
        bucket: a69c003f-5281-4376-9875-ebac846ae7e9-wemove
  security:
    authentication: cookie
    token:
      jwt:
        cookie:
          cookie-secure: true
        signatures:
          secret:
            generator:
              secret: WeMoveChangeThisSecretForANewOne
    redirect:
      login-success: http://localhost:3000
      login-failure: http://localhost:8080/failed-auth
      logout: http://localhost:8080
    oauth2:
      login-uri: "/api/oauth/login{/provider}"
      callback-uri: "/api/oauth/callback{/provider}"
      clients:
        google:
          client-id: "867150944261-toegpflg674bdoikca22l6bm5aaqm5kj.apps.googleusercontent.com"
          client-secret: "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"
          openid:
            authorization:
              prompt: select_account
            issuer: "https://accounts.google.com"
    endpoints:
      introspection:
        path: /api/token_info
      logout:
        path: /api/logout
        get-allowed: true
      login:
        path: /api/login
      oauth:
        path: /api/oauth/access_token
    intercept-url-map:
      - pattern: /favicon.ico
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /login-failed.html
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /info
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /assets/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /**
        http-method: GET
        access:
          - isAnonymous()
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      default:
        paths: classpath:public
        mapping: /**
        enabled: true
  server:
    cors:
      enabled: true
      configurations:
        allowedOrigins:
          - http://localhost:3000
          - localhost:3000
          - http://127.0.0.1:3000
  data:
    pageable:
      size-parameter-name: page_size
datasources:
  default:
    db-type: ${WEMOVE_DB_TYPE}
jpa:
  default:
    entity-scan:
      packages: "app.model"
    properties:
      hibernate:
        hbm2ddl:
          auto: ${WEMOVE_AUTO_SCHEMA_GEN:update}
netty:
  default:
    allocator:
      max-order: 3
wemove:
  image-storage:
    bucket-url-format: "https://storage.googleapis.com/%s/"
    bucket: "micronaut.object-storage.gcp.default.bucket"
    append-object-url-format: "%s"
  recaptcha:
    secret: "6LfY3tMlAAAAAAxsA68VyjGMkbIkBqql3gDLG-Hs"
  safesearch:
    key: "AIzaSyC_RuNsPOuWzMq7oiWNDxJoiqGZrOky9Kk"