name: Build And Test With Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        env:
          MICRONAUT_ENVIRONMENTS: h2
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: 'app:build'
      - name: Build with Gradle - MySQL Datasource
        if: ${{ success() }}
        env:
          WEMOVE_DATABASE_DEPENDENCY: mysql:mysql-connector-java:8.0.31
          WEMOVE_DB_TYPE: mysql
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: 'app:build'
      - name: Build with Gradle - PostgreSQL Datasource
        if: ${{ success() }}
        env:
          WEMOVE_DATABASE_DEPENDENCY: org.postgresql:postgresql:42.4.2
          WEMOVE_DB_TYPE: postgres
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: 'app:build'
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'app/build/test-results/**/*.xml'
          detailed_summary: true
          include_passed: true
