name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run the server with Gradle
      env:
        VITE_BACKEND_URL: /api
        MICRONAUT_ENVIRONMENTS: dev,dev-data
      run: |
        ./gradlew app:run &
    - name: Create and populate .env file
      working-directory: ./frontend
      env:
        VITE_BACKEND_URL: /api
        VITE_GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
          touch .env
          echo VITE_BACKEND_URL="$VITE_BACKEND_URL" >> .env
          echo VITE_GOOGLE_API_KEY="$VITE_GOOGLE_API_KEY" >> .env

          echo "cat .env"
          cat .env
      shell: bash
    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./frontend
    - name: Run Playwright tests
      run: npx playwright test
      working-directory: ./frontend
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
